name: Run Python Script and Push Changes

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8' # Specify the Python version you need

    - name: Clone and clean repository
      run: |
        source .env
        git clone https://github.com/SakamichiSeries/${REPO_NAME}.git
        shopt -s extglob
        rm -rf ${REPO_NAME}/!(.git)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # - name: Run Python script
    #   run: python nogizaka.py

    - name: Change directory
      run: |
        source .env
        pwd
        cd ${REPO_NAME}
        pwd

    - name: Copy .nojekyll
      run: |
        pwd
        cp ../.nojekyll .

    - name: Commit changes
      run: |
        git config --local user.name "GitHub Action"
        git config --local user.email "action@github.com"
        git add .
        git commit -m "Automated commit by GitHub Action"

    - name: Push changes
      run: git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}