name: scraper

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
          token: ${{ secrets.Token_GitHub }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8' # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # - name: Run Python script
    #   run: python Nogizaka46.py
    #   env:
    #     TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
    
    - name: Run Python script
      run: python Keyakizaka46.py
      env:
        TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
       
    # - name: Run Python script
    #   run: python Hinatazaka46.py
    #   env:
    #     TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
